<?php

namespace Tigralt\EZNotificationBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNb($user_id = null) {
        $builder = $this->createQueryBuilder('o');

        if(is_null($user_id)) {
            return $builder
                ->select($builder->expr()->count('o'))
                ->getQuery()
                ->getSingleScalarResult();
        }

        return $builder
            ->select($builder->expr()->count('o'))
            ->where('o.userId = :u')
            ->setParameter('u', $user_id)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getNbNotSeen($user_id = null) {
        $builder = $this->createQueryBuilder('o');

        if(is_null($user_id)) {
            return $builder
                ->select($builder->expr()->count('o'))
                ->where('o.seen = 0')
                ->getQuery()
                ->getSingleScalarResult();
        }

        return $builder
            ->select($builder->expr()->count('o'))
            ->where('o.userId = :u')
            ->setParameter('u', $user_id)
            ->andWhere('o.seen = 0')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
